sudo: enabled

language: C++

env:
  - SH=bash

before_install:
  - chmod +x ./travis-ci/install-boost-1.56.sh
  - ./travis-ci/install-boost-1.56.sh
  - chmod +x ./travis-ci/install-zeromq-4.2.1.sh
  - ./travis-ci/install-zeromq-4.2.1.sh
